name: apply

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: hashicorp/setup-terraform@v1

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Get Secret
        run: echo '${{ secrets.GOOGLE_CREDS }}' > creds.json

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Apply
        id: plan
        run: terraform apply -no-color -auto-approve

      - name: Get App Private Key
        run: echo '${{ secrets.APP_KEY }}' > pk.pem

      - name: Generate Token
        id: token
        run: |
          TOKEN="$(npx obtain-github-app-installation-access-token -a 164080 -i 22180275 -k ./pk.pem)"
          echo "::add-mask::$TOKEN"
          echo "::set-output name=token::$TOKEN"

      - name: Commit State
        uses: github-actions-x/commit@v2.8
        with:
          github-token: ${{ steps.token.outputs.token }}
          push-branch: 'main'
          commit-message: '[ci skip] save state'
          force-add: 'false'
          files: terraform.tfstate

