name: check

on:
  pull_request:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
      - name: Init
        run: terraform init
      - name: Lint
        run: terraform fmt -check
      - name: Get Secret
        run: echo '${{ secrets.google_creds }}' > creds.json
      - name: Validate
        run: terraform validate -no-color
